# Generated by Django 5.0.3 on 2024-03-11 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lc_questions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='hidden_test_cases',
        ),
        migrations.RemoveField(
            model_name='question',
            name='sample_test_cases',
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_input_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_input_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_input_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_output_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_output_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='hidden_output_3',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_input_2',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output_1',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='question',
            name='sample_output_2',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
